version: "3.8"
services:
  robot:
    build:
      context: .
      dockerfile: foxy.Dockerfile
    container_name: robot
    network_mode: "host"
    privileged: true
    volumes:
    - .:/ws_bot
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    stdin_open: true
    tty: true
    entrypoint: /ros_entrypoint.sh
    command: /bin/bash
  rviz:
    build:
      context: .
      dockerfile: foxy.Dockerfile
    container_name: rviz
    network_mode: "host"
    privileged: true
    volumes:
    - .:/ws_bot
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    entrypoint: /ros_entrypoint.sh
    command: rviz2
  gazebo:
    build:
      context: .
      dockerfile: gazebo.Dockerfile
    container_name: gazebo
    network_mode: "host"
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    entrypoint: /ros_entrypoint.sh
    command: gazebo
