services:
  robot:
    build:
      context: .
      dockerfile: jazzy.Dockerfile
    container_name: robot
    network_mode: "host"
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - .:/ws_bot
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    stdin_open: true
    tty: true
    entrypoint: /ros_entrypoint.sh
    command: bash
  rviz:
    build:
      context: .
      dockerfile: jazzy.Dockerfile
    container_name: rviz
    network_mode: "host"
    depends_on:
      - robot
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - ROS_IP=robot
    volumes:
      - .:/ws_bot
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    stdin_open: true
    tty: true
    entrypoint: /ros_entrypoint.sh
    command: ros2 run rviz2 rviz2
  gazebo:
    build:
      context: .
      dockerfile: gazebo.jazzy.Dockerfile
    container_name: gazebo
    network_mode: "host"
    depends_on:
      - robot
      - rviz
    privileged: true
    devices:
      - /dev/snd:/dev/snd  # Add audio devices
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse
      - /etc/localtime:/etc/localtime:ro
    entrypoint: /ros_entrypoint.sh
    command: gz sim
